### ISSUE TITLE
Incorrect shebang for Python script with Noetic

### ISSUE THREAD

**Issue by BenjaminNavarro** [ros/ros_tutorials#115] opened 2021-03-12 10:33 UTC
With Noetic, ROS has switched to Python 3 but the scripts in the tutorials still refer to `python`in their shebang:
```
#!/usr/bin/env python
```
but `python` doesn't exist on Ubuntu 20.04 so the script will just fail to run with:
```
/usr/bin/env: ‘python’: No such file or directory
```
Starting from Noetic the proper shebang is:
```
#!/usr/bin/env python3
```
This should be fixed in this repo and in the wiki

**Comment by mabelzhang** [comment] 2021-03-12 23:52
This is actually by design. We document the python3 shebang specific to ROS here http://wiki.ros.org/UsingPython3/SourceCodeChanges#Changing_shebangs

`python` is the correct shebang. `catkin_install_python`, which is called from `CMakeLists.txt`, will automatically append the `3` as needed.

**Comment by mabelzhang** [comment] 2021-03-16 00:31
Closing as I think it has been answered. Feel free to reopen.

**Closed as completed by mabelzhang** 2021-03-16 00:31 UTC
Labels: question

**Comment by BenjaminNavarro** [comment] 2021-03-19 11:14
Ok, I didn't know, probably because I mostly use C++ and not Python
