### ISSUE TITLE
turtlesim does not shut down correctly

### ISSUE THREAD

**Issue by chadrockey** [ros/ros_tutorials#3] opened 2012-11-21 01:42 UTC
For this tutorial:
http://www.ros.org/wiki/ROS/Tutorials/UnderstandingNodes

Turtlesim doesn't seem to ctrl-c correctly and unassociate from the master, producing an error later on in the tutorial:

rosnode list
                /my_turtle
                /rosout
                /turtlesim

**Comment by dirk-thomas** [comment] 2012-12-05 09:37
I can't reproduce the issue anymore. Likely it has been resolved with rospack 2.1.13 which removes wrongly installed signal handlers of the embedded Python interpreter.

**Closed as completed by dirk-thomas** 2012-12-05 09:37 UTC
Labels: bug
