### ISSUE TITLE
[ROS 2] Invalid context error when stopping turtle_teleop_key

### ISSUE THREAD

**Issue by jacobperron** [ros/ros_tutorials#86] opened 2020-05-21 22:38 UTC
Sometimes during the shutdown of turtle_teleop_key (i.e. Ctrl-C), we see the following error:

```
[ERROR] [1590100346.240527469] [rclcpp]: failed to create wait set: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-foxy-rcl-1.0.0/src/rcl/wait.c:128
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create wait set in Executor constructor
```

Looks like an issue with the signal handling logic.

I've seen the same behavior with Fast-RTPS and CycloneDDS.

**Comment by ivanpauno** [comment] 2020-05-28 20:45
Looks like duplicate of https://github.com/ros2/rclcpp/issues/1139.

**Comment by ivanpauno** [comment] 2020-06-25 18:03
Closing in favor of https://github.com/ros2/rclcpp/issues/1139

**Closed as completed by ivanpauno** 2020-06-25 18:03 UTC
Labels: bug

**Comment by jacobperron** [comment] 2020-07-10 20:47
Note, this was a bug that came up during Foxy testing. It would be nice if a solution to ros2/rclcpp#1139 could be backported to Foxy.
